# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo

pod 'AFNetworking', '~> 3.0’  
pod 'Masonry', '~> 0.6.4'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'RongCloudIMKit'
  target 'DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
